//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscoProxyTest.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01", ConfigurationName="ServiceReference1.DiscoveryProxy")]
    public interface DiscoveryProxy {
        
        // CODEGEN: Generating message contract since the operation ProbeOperation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01/Probe", ReplyAction="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01/ProbeMatches")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProblemActionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributedAnyType))]
        DiscoProxyTest.ServiceReference1.ProbeMatchesMessage11 ProbeOperation(DiscoProxyTest.ServiceReference1.ProbeMessage11 request);
        
        // CODEGEN: Generating message contract since the operation ResolveOperation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01/Resolve", ReplyAction="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01/ResolveMatches")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProblemActionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributedAnyType))]
        DiscoProxyTest.ServiceReference1.ResolveMatchesMessage11 ResolveOperation(DiscoProxyTest.ServiceReference1.ResolveMessage11 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01")]
    public partial class ProbeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typesField;
        
        private ScopesType scopesField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Types {
            get {
                return this.typesField;
            }
            set {
                this.typesField = value;
                this.RaisePropertyChanged("Types");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ScopesType Scopes {
            get {
                return this.scopesField;
            }
            set {
                this.scopesField = value;
                this.RaisePropertyChanged("Scopes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01")]
    public partial class ScopesType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string matchByField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string MatchBy {
            get {
                return this.matchByField;
            }
            set {
                this.matchByField = value;
                this.RaisePropertyChanged("MatchBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string[] Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01")]
    public partial class AppSequenceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class ProblemActionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AttributedURIType actionField;
        
        private string soapActionField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AttributedURIType Action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("Action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="anyURI", Order=1)]
        public string SoapAction {
            get {
                return this.soapActionField;
            }
            set {
                this.soapActionField = value;
                this.RaisePropertyChanged("SoapAction");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class AttributedURIType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class AttributedAnyType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01")]
    public partial class ResolveMatches11 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ProbeMatchType resolveMatchField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public ProbeMatchType ResolveMatch {
            get {
                return this.resolveMatchField;
            }
            set {
                this.resolveMatchField = value;
                this.RaisePropertyChanged("ResolveMatch");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01")]
    public partial class ProbeMatchType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EndpointReferenceType endpointReferenceField;
        
        private string typesField;
        
        private ScopesType scopesField;
        
        private string xAddrsField;
        
        private uint metadataVersionField;
        
        private bool metadataVersionFieldSpecified;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2005/08/addressing", Order=0)]
        public EndpointReferenceType EndpointReference {
            get {
                return this.endpointReferenceField;
            }
            set {
                this.endpointReferenceField = value;
                this.RaisePropertyChanged("EndpointReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Types {
            get {
                return this.typesField;
            }
            set {
                this.typesField = value;
                this.RaisePropertyChanged("Types");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ScopesType Scopes {
            get {
                return this.scopesField;
            }
            set {
                this.scopesField = value;
                this.RaisePropertyChanged("Scopes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string XAddrs {
            get {
                return this.xAddrsField;
            }
            set {
                this.xAddrsField = value;
                this.RaisePropertyChanged("XAddrs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public uint MetadataVersion {
            get {
                return this.metadataVersionField;
            }
            set {
                this.metadataVersionField = value;
                this.RaisePropertyChanged("MetadataVersion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MetadataVersionSpecified {
            get {
                return this.metadataVersionFieldSpecified;
            }
            set {
                this.metadataVersionFieldSpecified = value;
                this.RaisePropertyChanged("MetadataVersionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=5)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class EndpointReferenceType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AttributedURIType addressField;
        
        private ReferenceParametersType referenceParametersField;
        
        private MetadataType metadataField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AttributedURIType Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ReferenceParametersType ReferenceParameters {
            get {
                return this.referenceParametersField;
            }
            set {
                this.referenceParametersField = value;
                this.RaisePropertyChanged("ReferenceParameters");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MetadataType Metadata {
            get {
                return this.metadataField;
            }
            set {
                this.metadataField = value;
                this.RaisePropertyChanged("Metadata");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=3)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class ReferenceParametersType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2005/08/addressing")]
    public partial class MetadataType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01")]
    public partial class ResolveType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EndpointReferenceType endpointReferenceField;
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2005/08/addressing", Order=0)]
        public EndpointReferenceType EndpointReference {
            get {
                return this.endpointReferenceField;
            }
            set {
                this.endpointReferenceField = value;
                this.RaisePropertyChanged("EndpointReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
                this.RaisePropertyChanged("Any");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProbeMessage11 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DiscoProxyTest.ServiceReference1.ProbeType Probe;
        
        public ProbeMessage11() {
        }
        
        public ProbeMessage11(DiscoProxyTest.ServiceReference1.ProbeType Probe) {
            this.Probe = Probe;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ProbeMatchesMessage11 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DiscoProxyTest.ServiceReference1.AppSequenceType AppSequence;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ProbeMatch")]
        public DiscoProxyTest.ServiceReference1.ProbeMatchType[] ProbeMatches;
        
        public ProbeMatchesMessage11() {
        }
        
        public ProbeMatchesMessage11(DiscoProxyTest.ServiceReference1.AppSequenceType AppSequence, DiscoProxyTest.ServiceReference1.ProbeMatchType[] ProbeMatches) {
            this.AppSequence = AppSequence;
            this.ProbeMatches = ProbeMatches;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResolveMessage11 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DiscoProxyTest.ServiceReference1.ResolveType Resolve;
        
        public ResolveMessage11() {
        }
        
        public ResolveMessage11(DiscoProxyTest.ServiceReference1.ResolveType Resolve) {
            this.Resolve = Resolve;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ResolveMatchesMessage11 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DiscoProxyTest.ServiceReference1.AppSequenceType AppSequence;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DiscoProxyTest.ServiceReference1.ResolveMatches11 ResolveMatches;
        
        public ResolveMatchesMessage11() {
        }
        
        public ResolveMatchesMessage11(DiscoProxyTest.ServiceReference1.AppSequenceType AppSequence, DiscoProxyTest.ServiceReference1.ResolveMatches11 ResolveMatches) {
            this.AppSequence = AppSequence;
            this.ResolveMatches = ResolveMatches;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DiscoveryProxyChannel : DiscoProxyTest.ServiceReference1.DiscoveryProxy, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiscoveryProxyClient : System.ServiceModel.ClientBase<DiscoProxyTest.ServiceReference1.DiscoveryProxy>, DiscoProxyTest.ServiceReference1.DiscoveryProxy {
        
        public DiscoveryProxyClient() {
        }
        
        public DiscoveryProxyClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiscoveryProxyClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiscoveryProxyClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiscoveryProxyClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiscoProxyTest.ServiceReference1.ProbeMatchesMessage11 DiscoProxyTest.ServiceReference1.DiscoveryProxy.ProbeOperation(DiscoProxyTest.ServiceReference1.ProbeMessage11 request) {
            return base.Channel.ProbeOperation(request);
        }
        
        public DiscoProxyTest.ServiceReference1.AppSequenceType ProbeOperation(DiscoProxyTest.ServiceReference1.ProbeType Probe, out DiscoProxyTest.ServiceReference1.ProbeMatchType[] ProbeMatches) {
            DiscoProxyTest.ServiceReference1.ProbeMessage11 inValue = new DiscoProxyTest.ServiceReference1.ProbeMessage11();
            inValue.Probe = Probe;
            DiscoProxyTest.ServiceReference1.ProbeMatchesMessage11 retVal = ((DiscoProxyTest.ServiceReference1.DiscoveryProxy)(this)).ProbeOperation(inValue);
            ProbeMatches = retVal.ProbeMatches;
            return retVal.AppSequence;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DiscoProxyTest.ServiceReference1.ResolveMatchesMessage11 DiscoProxyTest.ServiceReference1.DiscoveryProxy.ResolveOperation(DiscoProxyTest.ServiceReference1.ResolveMessage11 request) {
            return base.Channel.ResolveOperation(request);
        }
        
        public DiscoProxyTest.ServiceReference1.AppSequenceType ResolveOperation(DiscoProxyTest.ServiceReference1.ResolveType Resolve, out DiscoProxyTest.ServiceReference1.ResolveMatches11 ResolveMatches) {
            DiscoProxyTest.ServiceReference1.ResolveMessage11 inValue = new DiscoProxyTest.ServiceReference1.ResolveMessage11();
            inValue.Resolve = Resolve;
            DiscoProxyTest.ServiceReference1.ResolveMatchesMessage11 retVal = ((DiscoProxyTest.ServiceReference1.DiscoveryProxy)(this)).ResolveOperation(inValue);
            ResolveMatches = retVal.ResolveMatches;
            return retVal.AppSequence;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01", ConfigurationName="ServiceReference1.Client")]
    public interface Client {
        
        // CODEGEN: Generating message contract since the operation HelloOperation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01/Hello")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProblemActionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributedAnyType))]
        void HelloOperation(DiscoProxyTest.ServiceReference1.HelloMessage11 request);
        
        // CODEGEN: Generating message contract since the operation ByeOperation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01/Bye")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ProblemActionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AttributedAnyType))]
        void ByeOperation(DiscoProxyTest.ServiceReference1.ByeMessage11 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloMessage11 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DiscoProxyTest.ServiceReference1.AppSequenceType AppSequence;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DiscoProxyTest.ServiceReference1.ProbeMatchType Hello;
        
        public HelloMessage11() {
        }
        
        public HelloMessage11(DiscoProxyTest.ServiceReference1.AppSequenceType AppSequence, DiscoProxyTest.ServiceReference1.ProbeMatchType Hello) {
            this.AppSequence = AppSequence;
            this.Hello = Hello;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ByeMessage11 {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01")]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DiscoProxyTest.ServiceReference1.AppSequenceType AppSequence;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://docs.oasis-open.org/ws-dd/ns/discovery/2009/01", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DiscoProxyTest.ServiceReference1.ProbeMatchType Bye;
        
        public ByeMessage11() {
        }
        
        public ByeMessage11(DiscoProxyTest.ServiceReference1.AppSequenceType AppSequence, DiscoProxyTest.ServiceReference1.ProbeMatchType Bye) {
            this.AppSequence = AppSequence;
            this.Bye = Bye;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientChannel : DiscoProxyTest.ServiceReference1.Client, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientClient : System.ServiceModel.ClientBase<DiscoProxyTest.ServiceReference1.Client>, DiscoProxyTest.ServiceReference1.Client {
        
        public ClientClient() {
        }
        
        public ClientClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void DiscoProxyTest.ServiceReference1.Client.HelloOperation(DiscoProxyTest.ServiceReference1.HelloMessage11 request) {
            base.Channel.HelloOperation(request);
        }
        
        public void HelloOperation(DiscoProxyTest.ServiceReference1.AppSequenceType AppSequence, DiscoProxyTest.ServiceReference1.ProbeMatchType Hello) {
            DiscoProxyTest.ServiceReference1.HelloMessage11 inValue = new DiscoProxyTest.ServiceReference1.HelloMessage11();
            inValue.AppSequence = AppSequence;
            inValue.Hello = Hello;
            ((DiscoProxyTest.ServiceReference1.Client)(this)).HelloOperation(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void DiscoProxyTest.ServiceReference1.Client.ByeOperation(DiscoProxyTest.ServiceReference1.ByeMessage11 request) {
            base.Channel.ByeOperation(request);
        }
        
        public void ByeOperation(DiscoProxyTest.ServiceReference1.AppSequenceType AppSequence, DiscoProxyTest.ServiceReference1.ProbeMatchType Bye) {
            DiscoProxyTest.ServiceReference1.ByeMessage11 inValue = new DiscoProxyTest.ServiceReference1.ByeMessage11();
            inValue.AppSequence = AppSequence;
            inValue.Bye = Bye;
            ((DiscoProxyTest.ServiceReference1.Client)(this)).ByeOperation(inValue);
        }
    }
}
