//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeploymentUpdate.Service.UI.Interface.Configuration {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MailAddressSurrogate", Namespace="http://schemas.datacontract.org/2004/07/DeploymentUpdate.DTO")]
    [System.SerializableAttribute()]
    public partial class MailAddressSurrogate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DisplayNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DisplayName {
            get {
                return this.DisplayNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DisplayNameField, value) != true)) {
                    this.DisplayNameField = value;
                    this.RaisePropertyChanged("DisplayName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Configuration.IConfigurationService")]
    public interface IConfigurationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetRecipients", ReplyAction="http://tempuri.org/IConfigurationService/GetRecipientsResponse")]
        System.Collections.Generic.List<DeploymentUpdate.Service.UI.Interface.Configuration.MailAddressSurrogate> GetRecipients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/UpdateRecipients", ReplyAction="http://tempuri.org/IConfigurationService/UpdateRecipientsResponse")]
        void UpdateRecipients(System.Collections.Generic.List<DeploymentUpdate.Service.UI.Interface.Configuration.MailAddressSurrogate> recipients);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetWatcherPath", ReplyAction="http://tempuri.org/IConfigurationService/GetWatcherPathResponse")]
        string GetWatcherPath();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/UpdateWatcherPath", ReplyAction="http://tempuri.org/IConfigurationService/UpdateWatcherPathResponse")]
        void UpdateWatcherPath(string watherPath);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/GetUriToWatchPath", ReplyAction="http://tempuri.org/IConfigurationService/GetUriToWatchPathResponse")]
        string GetUriToWatchPath();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IConfigurationService/UpdateUriToWatchPath", ReplyAction="http://tempuri.org/IConfigurationService/UpdateUriToWatchPathResponse")]
        void UpdateUriToWatchPath(string uriToWathPath);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IConfigurationServiceChannel : DeploymentUpdate.Service.UI.Interface.Configuration.IConfigurationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConfigurationServiceClient : System.ServiceModel.ClientBase<DeploymentUpdate.Service.UI.Interface.Configuration.IConfigurationService>, DeploymentUpdate.Service.UI.Interface.Configuration.IConfigurationService {
        
        public ConfigurationServiceClient() {
        }
        
        public ConfigurationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConfigurationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConfigurationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<DeploymentUpdate.Service.UI.Interface.Configuration.MailAddressSurrogate> GetRecipients() {
            return base.Channel.GetRecipients();
        }
        
        public void UpdateRecipients(System.Collections.Generic.List<DeploymentUpdate.Service.UI.Interface.Configuration.MailAddressSurrogate> recipients) {
            base.Channel.UpdateRecipients(recipients);
        }
        
        public string GetWatcherPath() {
            return base.Channel.GetWatcherPath();
        }
        
        public void UpdateWatcherPath(string watherPath) {
            base.Channel.UpdateWatcherPath(watherPath);
        }
        
        public string GetUriToWatchPath() {
            return base.Channel.GetUriToWatchPath();
        }
        
        public void UpdateUriToWatchPath(string uriToWathPath) {
            base.Channel.UpdateUriToWatchPath(uriToWathPath);
        }
    }
}
